branches:
  - master
  - release

build:
  image: aplazame/nodejs-karma:phantomjs
  environment:
    - GITHUB_TOKEN=$$GITHUB_TOKEN
  commands:
    - 'make build'

deploy:
  rsync:
    user: $$DEPLOY_USER
    host: dev.aplazame.com
    target: $$DEPLOY_PATH
    delete: true
    recursive: true
    exclude:
      - ".git"
      - "node_modules"
      - ".bower_components"
    when:
      branch: master

  rsync:
    user: $$RELEASE_USER
    host: aplazame.com
    target: $$RELEASE_PATH
    delete: true
    recursive: true
    exclude:
      - ".git"
      - "node_modules"
      - ".bower_components"
    when:
      branch: release

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'drone'
    channel: 'developers'
    when:
      success: false
      failure: true
      change: true

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASS
    recipients:
      - dev@aplazame.com
    when:
      success: false
      failure: true
      change: true
