build:
  image: aplazame/nodejs-karma:0.7.3
  environment:
    - GITHUB_TOKEN=$$GITHUB_TOKEN
    - AWS_ACCESS_KEY_ID=$$S3_ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY=$$S3_SECRET_KEY
  commands:
    - 'sed -i "s/git@github.com:/http:\/\/$GITHUB_TOKEN:x-oauth-basic@github.com\//g" bower.json'
    - 'echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc'
    - 'make build'

deploy:
  rsync:
    user: ec2-user
    host: 18.196.173.0
    source: dist/
    target: /mnt/frontend/aplazame-js
    delete: true
    recursive: true
    when:
      branch: master

  rsync:
    user: ec2-user
    host: 18.196.173.0
    source: public/
    target: /mnt/frontend/demo-site
    delete: true
    recursive: true
    when:
      branch: master

  rsync:
    user: $$DEPLOY_USER
    host: aplazame.com
    target: $$DEPLOY_PATH
    delete: true
    recursive: true
    exclude:
      - ".git"
      - "node_modules"
      - ".bower_components"
    when:
      branch: release

  rsync:
    user: ubuntu
    host: demo.aplazame.org
    source: public/
    target: ~/www/demo-demo
    delete: true
    recursive: true
    when:
      branch: demo
