branches:
  - master
  - release

build:
  image: aplazame/nodejs-karma:0.3.2
  environment:
    - GITHUB_TOKEN=$$GITHUB_TOKEN
  commands:
    - 'sed -i "s/git@github.com:/http:\/\/$GITHUB_TOKEN:x-oauth-basic@github.com\//" bower.json'
    - 'make test'

deploy:
  rsync:
    user: $$DEPLOY_USER
    host: demo.debug.aplazame.com
    target: $$DEBUG_PATH
    delete: true
    recursive: true
    when:
      branch: master

  rsync:
    user: $$DEPLOY_USER
    host: demo.aplazame.com
    target: $$RELEASE_PATH
    delete: true
    recursive: true
    when:
      branch: release

  rsync:
    user: $$DEPLOY_USER
    host: aplazame.com
    target: $$RELEASE_PATH
    delete: true
    recursive: true
    when:
      branch: release

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'drone'
    channel: 'developers'
    when:
      success: false
      failure: true
      change: true

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASS
    recipients:
      - dev@aplazame.com
    when:
      success: false
      failure: true
      change: true
