build:
  image: aplazame/nodejs-karma:0.7.4
  environment:
    - GITHUB_TOKEN=$$GITHUB_TOKEN
    - AWS_ACCESS_KEY_ID=$$S3_ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY=$$S3_SECRET_KEY
  commands:
    # - 'sed -i "s/git+ssh:\/\/github.com\/aplazame\//https:\/\/$GITHUB_TOKEN:x-oauth-basic@github.com\/aplazame\//" package.json'
    - 'echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc'
    - 'make build'

deploy:
  rsync:
    user: $$DEPLOY_USER_DEV
    host: deploy-dev.aplazame.org
    source: dist/
    target: ~/www/frontend/aplazame-js
    delete: true
    recursive: true
    when:
      branch: master

  rsync:
    user: $$DEPLOY_USER_DEV
    host: deploy-dev.aplazame.org
    source: public/
    target: ~/www/frontend/demo-site
    delete: true
    recursive: true
    when:
      branch: master

  rsync:
    user: $$DEPLOY_USER_PROD
    host: deploy-prod.aplazame.org
    source: dist/
    target: ~/www/frontend/aplazame-js
    delete: true
    recursive: true
    when:
      branch: release

  rsync:
    user: $$DEPLOY_USER_PROD
    host: deploy-prod.aplazame.org
    source: public/
    target: ~/www/frontend/demo-site
    delete: true
    recursive: true
    when:
      branch: release

  rsync:
    user: ubuntu
    host: demo.aplazame.org
    source: public/
    target: ~/www/demo-demo
    delete: true
    recursive: true
    when:
      branch:
        - demo
