version: "2.1"

services:
  application:
    build:
      context: ./
      args:
        - GITHUB_TOKEN
    entrypoint: make live
    env_file:
      - ./.env
    ports:
      - 80:8080
      - 12321:12321
    volumes:
      - ./demo:/project/demo
      - ./src:/project/src
      - ./widgets:/project/widgets
