
production:
  url_aplazame_js: https://cdn.aplazame.com/aplazame.js
  url_api: https://api.aplazame.com/
  url_checkout: https://checkout.aplazame.com/
  url_widgets: https://cdn.aplazame.com/widgets/

development:
  url_aplazame_js: https://cdn-dev.aplazame.com/aplazame.js  
  url_api: https://api-dev.aplazame.com/
  url_checkout: https://checkout-dev.aplazame.com/
  url_widgets: https://cdn-dev.aplazame.com/widgets/

  demo:
    url_aplazame_js: /dist/aplazame.js
    url_api: https://api-dev.aplazame.com/
    url_checkout: https://checkout-dev.aplazame.com/
    url_widgets: /dist/widgets/
