commands:
  replace_cred:
    steps:
      - run:
          name: 'Add credentials for cloning properly via HTTPS instead of SSH'
          command: sed -i "s/git+ssh:\/\/git@github.com\/aplazame\//https:\/\/$GITHUB_TOKEN:x-oauth-basic@github.com\/aplazame\//" package-lock.json &&
            sed -i "s/git+ssh:\/\/git@github.com\/aplazame\//https:\/\/$GITHUB_TOKEN:x-oauth-basic@github.com\/aplazame\//" package.json
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - replace_cred
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run:
          name: Build application
          command: make build | sed --unbuffered 's/[[:alnum:]]*:x-oauth-basic//g'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  test_workflow:
    jobs:
      - build:
        filters:
          branches:
            only:
              - jasuch/ch9557/migración-de-los-procesos-de-despliegue




